base_url = "https://www.bunnings.com.au/"
log_file = "../Logs/log.txt"
title = "Bunnings Warehouse"
ScreenShot_Title = "../Logs/screenshot/BunningsWithTitle.png"
message = "Executed Successfully"
emailid = "hdummy030@gmail.com"
password = "pass@123"
term = "My Profile at Bunnings"
