# Generated by Selenium IDE

import time
import json
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium import webdriver
from selenium.webdriver.chrome.webdriver import WebDriver
from Pages.SignInPage import SignInPage

log_file = "../Logs/log.txt"
# Pass_message1 ="TC_1.a: Executed with search value : Drill || Successful"
Fail_message = "Failure Occurred"
driver = webdriver.Chrome()  # type: WebDriver
base_url = "https://www.bunnings.com.au/"
search_item = "drill"


def set_up():
    driver.get(base_url)
    driver.maximize_window()


def customer_log_recent_search():
    sp = SignInPage(driver)
    sp.Login()


def down():
    driver.quit()


set_up()
customer_log_recent_search()
# down()
